# FROM registry.access.redhat.com/ubi9/python-311:1-52.1712567218
# WORKDIR /chat
# COPY requirements.txt .
# RUN pip install --upgrade pip
# RUN pip install --no-cache-dir --upgrade -r /chat/requirements.txt
# COPY chatbot_ui.py .
# EXPOSE 8501
# ENTRYPOINT [ "streamlit", "run", "chatbot_ui.py" ]

## Stage 1 : build with maven builder image with native capabilities
FROM registry.access.redhat.com/ubi8/openjdk-21 AS build
COPY  pom.xml /home/jboss
COPY  .mvn /home/jboss/.mvn
COPY  mvnw /home/jboss/mvnw
WORKDIR /home/jboss/
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /home/jboss/src
RUN ./mvnw package

## Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi8/openjdk-21-runtime
WORKDIR /deployments/
COPY --from=build --chown=185 /home/jboss/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /home/jboss/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /home/jboss/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /home/jboss/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8501
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8501 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]